# Generated by Django 3.2.6 on 2021-08-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_text',
            new_name='order_name',
        ),
    ]
